#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
ENV_EXAMPLE_FILE="${ROOT_DIR}/.env.example"
DATA_SQLITE_DIR="${ROOT_DIR}/data/sqlite"
DATA_APP_DIR="${ROOT_DIR}/data/app"
DATA_BACKUPS_DIR="${ROOT_DIR}/data/backups"
DEFAULT_PORT="8000"
DEFAULT_ADMIN_USERNAME="admin"
DEFAULT_POSTGRES_DB="matrixmanager"
DEFAULT_POSTGRES_USER="matrixmanager"
DEFAULT_POSTGRES_SSLMODE="prefer"

require_command() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Error: required command '$cmd' is not installed or not in PATH." >&2
    exit 1
  fi
}

random_secret() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
}

prompt_with_default() {
  local prompt="$1"
  local default="$2"
  local value
  read -r -p "$prompt [$default]: " value
  if [[ -z "$value" ]]; then
    value="$default"
  fi
  printf '%s' "$value"
}

wait_for_http() {
  local url="$1"
  local attempts="${2:-60}"
  local sleep_seconds="${3:-2}"
  local i
  for ((i=1; i<=attempts; i++)); do
    if curl --fail --silent "$url" >/dev/null 2>&1; then
      return 0
    fi
    sleep "$sleep_seconds"
  done
  return 1
}

ensure_dir_or_fallback() {
  local preferred="$1"
  local fallback="$2"
  if mkdir -p "$preferred" 2>/dev/null; then
    printf '%s' "$preferred"
    return 0
  fi
  mkdir -p "$fallback"
  printf '%s' "$fallback"
}

require_command docker
require_command curl
require_command python3

if ! docker compose version >/dev/null 2>&1; then
  echo "Error: docker compose is required but not available." >&2
  exit 1
fi

mkdir -p "$DATA_SQLITE_DIR" "$DATA_APP_DIR"
DATA_BACKUPS_DIR="$(ensure_dir_or_fallback "$DATA_BACKUPS_DIR" "${ROOT_DIR}/backups")"

if [[ ! -f "$ENV_EXAMPLE_FILE" ]]; then
  echo "Error: .env.example is missing at $ENV_EXAMPLE_FILE" >&2
  exit 1
fi

echo "Matrix Manager beta installer"
echo "Project root: $ROOT_DIR"
echo

INSTALL_MODE="$(prompt_with_default "Install mode (postgresql/sqlite)" "postgresql")"
INSTALL_MODE="$(printf '%s' "$INSTALL_MODE" | tr '[:upper:]' '[:lower:]')"
if [[ "$INSTALL_MODE" != "sqlite" && "$INSTALL_MODE" != "postgresql" ]]; then
  echo "Error: install mode must be 'sqlite' or 'postgresql'." >&2
  exit 1
fi

APP_PORT="$(prompt_with_default "Host port for Matrix Manager" "$DEFAULT_PORT")"
ADMIN_USERNAME="$(prompt_with_default "Admin username" "$DEFAULT_ADMIN_USERNAME")"
read -r -s -p "Admin password (leave blank to auto-generate): " ADMIN_PASSWORD
echo
if [[ -z "$ADMIN_PASSWORD" ]]; then
  ADMIN_PASSWORD="$(random_secret)"
  GENERATED_ADMIN_PASSWORD="yes"
else
  GENERATED_ADMIN_PASSWORD="no"
fi

BASE_URL_DEFAULT="http://127.0.0.1:${APP_PORT}"
MATRIX_BASE_URL="$(prompt_with_default "Base URL" "$BASE_URL_DEFAULT")"
MATRIX_AUTH_SECRET="$(random_secret)"
MATRIX_SQLITE_PATH="/data/sqlite/matrix.db"
MATRIX_CONTROL_DB_PATH="/data/app/matrixmanager_control.db"
POSTGRES_HOST="postgres"
POSTGRES_PORT="5432"
POSTGRES_DB="$DEFAULT_POSTGRES_DB"
POSTGRES_USER="$DEFAULT_POSTGRES_USER"
POSTGRES_PASSWORD=""
POSTGRES_SSLMODE="$DEFAULT_POSTGRES_SSLMODE"

if [[ "$INSTALL_MODE" == "postgresql" ]]; then
  POSTGRES_DB="$(prompt_with_default "PostgreSQL database name" "$DEFAULT_POSTGRES_DB")"
  POSTGRES_USER="$(prompt_with_default "PostgreSQL username" "$DEFAULT_POSTGRES_USER")"
  read -r -s -p "PostgreSQL password (leave blank to auto-generate): " POSTGRES_PASSWORD
  echo
  if [[ -z "$POSTGRES_PASSWORD" ]]; then
    POSTGRES_PASSWORD="$(random_secret)"
  fi
fi

if [[ -f "$ENV_FILE" ]]; then
  read -r -p ".env already exists. Overwrite it? [y/N]: " OVERWRITE_ENV
  OVERWRITE_ENV="$(printf '%s' "$OVERWRITE_ENV" | tr '[:upper:]' '[:lower:]')"
  if [[ "$OVERWRITE_ENV" != "y" && "$OVERWRITE_ENV" != "yes" ]]; then
    echo "Aborting without modifying existing .env"
    exit 1
  fi
fi

cat > "$ENV_FILE" <<EOF
# Generated by install.sh
MATRIX_INSTALL_MODE=${INSTALL_MODE}
MATRIX_ACTIVE_DB_TYPE=${INSTALL_MODE}
MATRIX_AUTH_USERNAME=${ADMIN_USERNAME}
MATRIX_AUTH_PASSWORD=${ADMIN_PASSWORD}
MATRIX_AUTH_SECRET=${MATRIX_AUTH_SECRET}
MATRIX_APP_PORT=${APP_PORT}
MATRIX_BASE_URL=${MATRIX_BASE_URL}
MATRIX_SQLITE_PATH=${MATRIX_SQLITE_PATH}
MATRIX_CONTROL_DB_PATH=${MATRIX_CONTROL_DB_PATH}
POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
EOF

cd "$ROOT_DIR"

if [[ "$INSTALL_MODE" == "postgresql" ]]; then
  echo "Starting Matrix Manager with bundled PostgreSQL..."
  docker compose --profile postgres up -d --build
else
  echo "Starting Matrix Manager with SQLite..."
  docker compose up -d --build
fi

echo "Waiting for app health endpoint..."
if ! wait_for_http "http://127.0.0.1:${APP_PORT}/health" 60 2; then
  echo "Error: Matrix Manager did not become healthy in time." >&2
  echo
  echo "Try:" >&2
  echo "  docker compose ps" >&2
  echo "  docker compose logs app --tail=100" >&2
  if [[ "$INSTALL_MODE" == "postgresql" ]]; then
    echo "  docker compose logs postgres --tail=100" >&2
  fi
  exit 1
fi

echo
printf 'Install complete.\n\n'
printf 'URL: %s\n' "$MATRIX_BASE_URL"
printf 'Login page: %s/login\n' "$MATRIX_BASE_URL"
printf 'Admin username: %s\n' "$ADMIN_USERNAME"
if [[ "$GENERATED_ADMIN_PASSWORD" == "yes" ]]; then
  printf 'Admin password (generated): %s\n' "$ADMIN_PASSWORD"
else
  printf 'Admin password: [user-supplied]\n'
fi
printf 'Install mode: %s\n' "$INSTALL_MODE"
printf 'Config file: %s\n' "$ENV_FILE"
printf 'SQLite data dir: %s\n' "$DATA_SQLITE_DIR"
printf 'App data dir: %s\n' "$DATA_APP_DIR"
printf 'Backups dir: %s\n' "$DATA_BACKUPS_DIR"
printf '\nUseful commands:\n'
printf '  ./status.sh\n'
printf '  ./start.sh\n'
printf '  ./stop.sh\n'
printf '  ./reset.sh\n'
printf '  ./uninstall.sh\n'
printf '  docker compose logs app --tail=100\n'
if [[ "$INSTALL_MODE" == "postgresql" ]]; then
  printf '  docker compose --profile postgres logs postgres --tail=100\n'
fi
