import type { FastifyPluginAsync, FastifyReply } from 'fastify';
import { getSessionUsername } from '../auth/session.js';
import {
  createAssignment,
  createDemand,
  createEmployee,
  createJobCode,
  createOrganization,
  createProject,
  deleteAssignment,
  deleteDemand,
  deleteEmployee,
  deleteJobCode,
  deleteOrganization,
  deleteProject,
  formatWorkforceError,
  getDashboardData,
  listAssignments,
  listDemands,
  listEmployees,
  listJobCodes,
  listOrganizations,
  listProjects,
  updateAssignment,
  updateDashboardTrackedEmployees,
  updateDemand,
  updateEmployee,
  updateJobCode,
  updateOrganization,
  updateProject
} from '../features/workforce/service.js';
import { addAuditEntry, clearAuditLog, createDbConnection, createUser, deleteDbConnection, deleteInboxItem, deleteUser, getAccountSettings, getRuntimeOverview, isAdminUser, listAuditEntries, listDbConnections, listInboxItems, listUsers, markInboxItemRead, updateAccountSettings, updateDbConnection, updateUser, wipeDataStore } from '../features/admin/service.js';
import { buildGetStartedPage } from '../ui/get-started-page.js';
import { buildLoginPage } from '../ui/login-page.js';
import { buildAssignmentsPage, buildDemandsPage, buildEmployeesPage, buildJobCodesPage, buildOrganizationsPage, buildProjectsPage } from '../ui/workforce-pages.js';
import { buildAccountSettingsPage, buildAuditPage, buildDbManagementPage, buildInboxPage, buildRuntimePage, buildUsersPage } from '../ui/admin-pages.js';
import { buildReactPage } from '../ui/react-shell.js';

function renderLogin(app: Parameters<FastifyPluginAsync>[0], error = '', next = '/') { return buildLoginPage({ error, next, logoHref: app.config.logoHref, githubUrl: app.config.githubRepoUrl }); }
function redirectWithFlash(reply: FastifyReply, path: string, message: string) { return reply.redirect(path + '?flash=' + encodeURIComponent(message)); }
function renderReactAuthedPage(app: Parameters<FastifyPluginAsync>[0], page: 'canvas' | 'dashboard' | 'forecast', title: string, username: string, currentPath: '/canvas' | '/dashboard' | '/forecast', flash = '') {
  return buildReactPage({
    page,
    title,
    uiDevUrl: app.config.uiDevUrl,
    useDevServer: app.config.uiUseDevServer,
    props: { currentUser: username, currentPath, flash },
  });
}
function asBody(body: unknown): Record<string, unknown> { return (body ?? {}) as Record<string, unknown>; }
function checkboxValue(value: unknown): boolean { return value === 'on' || value === 'true' || value === true; }
function numberOrNull(value: unknown) { return value === '' || value == null ? null : Number(value); }
function numberOrDefault(value: unknown, fallback: number) { return value === '' || value == null ? fallback : Number(value); }
function stringOrNull(value: unknown) { const text = String(value ?? '').trim(); return text || null; }
function requireAdmin(reply: FastifyReply, username: string | null) { if (!username) return reply.redirect('/login'); if (!isAdminUser(username)) return redirectWithFlash(reply, '/', 'Admin access required.'); return null; }
function logAudit(actor: string, action: string, entityType: string, entityId: string | number, summary: string, before: unknown = null, after: unknown = null) { addAuditEntry({ actor, action, entity_type: entityType, entity_id: String(entityId), summary, before_json: before == null ? null : JSON.stringify(before, null, 2), after_json: after == null ? null : JSON.stringify(after, null, 2) }); }
function findById<T extends { id: number }>(items: T[], id: number) { return items.find((item) => item.id === id) ?? null; }

export const pageRoutes: FastifyPluginAsync = async (app) => {
  app.get('/', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2F'); return reply.type('text/html; charset=utf-8').send(buildGetStartedPage(username)); });
  app.get('/canvas', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fcanvas'); return reply.type('text/html; charset=utf-8').send(renderReactAuthedPage(app, 'canvas', 'Matrix Manager · Canvas', username, '/canvas', String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });
  app.get('/login', async (request, reply) => { if (getSessionUsername(request)) return reply.redirect('/'); const next = typeof request.query === 'object' && request.query && 'next' in request.query ? String((request.query as Record<string, unknown>).next ?? '/') : '/'; return reply.type('text/html; charset=utf-8').send(renderLogin(app, '', next)); });

  app.get('/orgs', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Forgs'); return reply.type('text/html; charset=utf-8').send(buildOrganizationsPage(username, listOrganizations(), String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });
  app.post('/orgs/create', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Forgs'); try { const body = asBody(request.body); const created = createOrganization({ name: String(body.name ?? '').trim(), description: stringOrNull(body.description) }); logAudit(username, 'create', 'organization', created.id, `Created organization ${created.name}`, null, created); return redirectWithFlash(reply, '/orgs', 'Organization created.'); } catch (error) { return redirectWithFlash(reply, '/orgs', formatWorkforceError(error).detail); } });
  app.post('/orgs/:organizationId/update', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Forgs'); try { const organizationId = Number((request.params as { organizationId: string }).organizationId); const before = findById(listOrganizations(), organizationId); const body = asBody(request.body); const updated = updateOrganization(organizationId, { name: String(body.name ?? '').trim(), description: stringOrNull(body.description) }); if (updated) logAudit(username, 'update', 'organization', organizationId, `Updated organization ${updated.name}`, before, updated); return redirectWithFlash(reply, '/orgs', 'Organization updated.'); } catch (error) { return redirectWithFlash(reply, '/orgs', formatWorkforceError(error).detail); } });
  app.post('/orgs/:organizationId/delete', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Forgs'); const organizationId = Number((request.params as { organizationId: string }).organizationId); const before = findById(listOrganizations(), organizationId); const result = deleteOrganization(organizationId); if (result.ok) logAudit(username, 'delete', 'organization', organizationId, `Deleted organization ${before?.name ?? organizationId}`, before, null); return redirectWithFlash(reply, '/orgs', result.ok ? 'Organization deleted.' : result.detail); });

  app.get('/job-codes', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fjob-codes'); return reply.type('text/html; charset=utf-8').send(buildJobCodesPage(username, listJobCodes(), String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });
  app.post('/job-codes/create', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fjob-codes'); try { const body = asBody(request.body); const created = createJobCode({ name: String(body.name ?? '').trim(), is_leader: checkboxValue(body.is_leader) }); logAudit(username, 'create', 'job_code', created.id, `Created job code ${created.name}`, null, created); return redirectWithFlash(reply, '/job-codes', 'Job code created.'); } catch (error) { return redirectWithFlash(reply, '/job-codes', formatWorkforceError(error).detail); } });
  app.post('/job-codes/:jobCodeId/update', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fjob-codes'); try { const jobCodeId = Number((request.params as { jobCodeId: string }).jobCodeId); const before = findById(listJobCodes(), jobCodeId); const body = asBody(request.body); const updated = updateJobCode(jobCodeId, { name: String(body.name ?? '').trim(), is_leader: checkboxValue(body.is_leader) }); if (updated) logAudit(username, 'update', 'job_code', jobCodeId, `Updated job code ${updated.name}`, before, updated); return redirectWithFlash(reply, '/job-codes', 'Job code updated.'); } catch (error) { return redirectWithFlash(reply, '/job-codes', formatWorkforceError(error).detail); } });
  app.post('/job-codes/:jobCodeId/delete', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fjob-codes'); const jobCodeId = Number((request.params as { jobCodeId: string }).jobCodeId); const before = findById(listJobCodes(), jobCodeId); const result = deleteJobCode(jobCodeId); if (result.ok) logAudit(username, 'delete', 'job_code', jobCodeId, `Deleted job code ${before?.name ?? jobCodeId}`, before, null); return redirectWithFlash(reply, '/job-codes', result.ok ? 'Job code deleted.' : result.detail); });

  app.get('/people', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fpeople'); return reply.type('text/html; charset=utf-8').send(buildEmployeesPage(username, listEmployees(), listOrganizations(), listJobCodes(), String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });
  app.post('/people/create', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fpeople'); try { const body = asBody(request.body); const created = createEmployee({ name: String(body.name ?? '').trim(), organization_id: Number(body.organization_id), job_code_id: Number(body.job_code_id), role: stringOrNull(body.role), location: stringOrNull(body.location), manager_id: numberOrNull(body.manager_id), capacity: numberOrDefault(body.capacity, 1) }); logAudit(username, 'create', 'employee', created.id, `Created employee ${created.name}`, null, created); return redirectWithFlash(reply, '/people', 'Employee created.'); } catch (error) { return redirectWithFlash(reply, '/people', formatWorkforceError(error).detail); } });
  app.post('/people/:employeeId/update', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fpeople'); try { const employeeId = Number((request.params as { employeeId: string }).employeeId); const before = findById(listEmployees(), employeeId); const body = asBody(request.body); const updated = updateEmployee(employeeId, { name: String(body.name ?? '').trim(), organization_id: Number(body.organization_id), job_code_id: Number(body.job_code_id), role: stringOrNull(body.role), location: stringOrNull(body.location), manager_id: numberOrNull(body.manager_id), capacity: numberOrDefault(body.capacity, 1) }); if (updated) logAudit(username, 'update', 'employee', employeeId, `Updated employee ${updated.name}`, before, updated); return redirectWithFlash(reply, '/people', 'Employee updated.'); } catch (error) { return redirectWithFlash(reply, '/people', formatWorkforceError(error).detail); } });
  app.post('/people/:employeeId/delete', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fpeople'); const employeeId = Number((request.params as { employeeId: string }).employeeId); const before = findById(listEmployees(), employeeId); const result = deleteEmployee(employeeId); if (result.ok) logAudit(username, 'delete', 'employee', employeeId, `Deleted employee ${before?.name ?? employeeId}`, before, null); return redirectWithFlash(reply, '/people', result.ok ? 'Employee deleted.' : result.detail); });

  app.get('/planning', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fplanning'); return reply.type('text/html; charset=utf-8').send(buildProjectsPage(username, listProjects(), String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });
  app.post('/planning/create', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fplanning'); try { const body = asBody(request.body); const created = createProject({ name: String(body.name ?? '').trim(), description: stringOrNull(body.description), start_date: stringOrNull(body.start_date), end_date: stringOrNull(body.end_date) }); logAudit(username, 'create', 'project', created.id, `Created project ${created.name}`, null, created); return redirectWithFlash(reply, '/planning', 'Project created.'); } catch (error) { return redirectWithFlash(reply, '/planning', formatWorkforceError(error).detail); } });
  app.post('/planning/:projectId/update', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fplanning'); try { const projectId = Number((request.params as { projectId: string }).projectId); const before = findById(listProjects(), projectId); const body = asBody(request.body); const updated = updateProject(projectId, { name: String(body.name ?? '').trim(), description: stringOrNull(body.description), start_date: stringOrNull(body.start_date), end_date: stringOrNull(body.end_date) }); if (updated) logAudit(username, 'update', 'project', projectId, `Updated project ${updated.name}`, before, updated); return redirectWithFlash(reply, '/planning', 'Project updated.'); } catch (error) { return redirectWithFlash(reply, '/planning', formatWorkforceError(error).detail); } });
  app.post('/planning/:projectId/delete', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fplanning'); const projectId = Number((request.params as { projectId: string }).projectId); const before = findById(listProjects(), projectId); const result = deleteProject(projectId); if (result.ok) logAudit(username, 'delete', 'project', projectId, `Deleted project ${before?.name ?? projectId}`, before, null); return redirectWithFlash(reply, '/planning', result.ok ? 'Project deleted.' : result.detail); });

  app.get('/demands', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fdemands'); return reply.type('text/html; charset=utf-8').send(buildDemandsPage(username, listDemands(), listProjects(), listOrganizations(), listJobCodes(), String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });
  app.post('/demands/create', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fdemands'); try { const body = asBody(request.body); const created = createDemand({ project_id: Number(body.project_id), title: String(body.title ?? '').trim(), organization_id: numberOrNull(body.organization_id), job_code_id: numberOrNull(body.job_code_id), skill_notes: stringOrNull(body.skill_notes), start_date: String(body.start_date ?? ''), end_date: String(body.end_date ?? ''), required_allocation: numberOrDefault(body.required_allocation, 1), notes: stringOrNull(body.notes) }); logAudit(username, 'create', 'demand', created.id, `Created demand ${created.title}`, null, created); return redirectWithFlash(reply, '/demands', 'Demand created.'); } catch (error) { return redirectWithFlash(reply, '/demands', formatWorkforceError(error).detail); } });
  app.post('/demands/:demandId/update', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fdemands'); try { const demandId = Number((request.params as { demandId: string }).demandId); const before = findById(listDemands(), demandId); const body = asBody(request.body); const updated = updateDemand(demandId, { project_id: Number(body.project_id), title: String(body.title ?? '').trim(), organization_id: numberOrNull(body.organization_id), job_code_id: numberOrNull(body.job_code_id), skill_notes: stringOrNull(body.skill_notes), start_date: String(body.start_date ?? ''), end_date: String(body.end_date ?? ''), required_allocation: numberOrDefault(body.required_allocation, 1), notes: stringOrNull(body.notes) }); if (updated) logAudit(username, 'update', 'demand', demandId, `Updated demand ${updated.title}`, before, updated); return redirectWithFlash(reply, '/demands', 'Demand updated.'); } catch (error) { return redirectWithFlash(reply, '/demands', formatWorkforceError(error).detail); } });
  app.post('/demands/:demandId/delete', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fdemands'); const demandId = Number((request.params as { demandId: string }).demandId); const before = findById(listDemands(), demandId); const result = deleteDemand(demandId); if (result.ok) logAudit(username, 'delete', 'demand', demandId, `Deleted demand ${before?.title ?? demandId}`, before, null); return redirectWithFlash(reply, '/demands', result.ok ? 'Demand deleted.' : result.detail); });

  app.get('/staffing', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fstaffing'); return reply.type('text/html; charset=utf-8').send(buildAssignmentsPage(username, listAssignments(), listEmployees(), listProjects(), listDemands(), String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });
  app.post('/staffing/create', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fstaffing'); try { const body = asBody(request.body); const created = createAssignment({ employee_id: Number(body.employee_id), project_id: Number(body.project_id), demand_id: numberOrNull(body.demand_id), start_date: String(body.start_date ?? ''), end_date: String(body.end_date ?? ''), allocation: numberOrDefault(body.allocation, 1), notes: stringOrNull(body.notes) }); logAudit(username, 'create', 'assignment', created.id, `Created assignment for ${created.employee_name ?? created.employee_id}`, null, created); return redirectWithFlash(reply, '/staffing', 'Assignment created.'); } catch (error) { return redirectWithFlash(reply, '/staffing', formatWorkforceError(error).detail); } });
  app.post('/staffing/:assignmentId/update', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fstaffing'); try { const assignmentId = Number((request.params as { assignmentId: string }).assignmentId); const before = findById(listAssignments(), assignmentId); const body = asBody(request.body); const updated = updateAssignment(assignmentId, { employee_id: Number(body.employee_id), project_id: Number(body.project_id), demand_id: numberOrNull(body.demand_id), start_date: String(body.start_date ?? ''), end_date: String(body.end_date ?? ''), allocation: numberOrDefault(body.allocation, 1), notes: stringOrNull(body.notes) }); if (updated) logAudit(username, 'update', 'assignment', assignmentId, `Updated assignment ${assignmentId}`, before, updated); return redirectWithFlash(reply, '/staffing', 'Assignment updated.'); } catch (error) { return redirectWithFlash(reply, '/staffing', formatWorkforceError(error).detail); } });
  app.post('/staffing/:assignmentId/delete', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fstaffing'); const assignmentId = Number((request.params as { assignmentId: string }).assignmentId); const before = findById(listAssignments(), assignmentId); const result = deleteAssignment(assignmentId); if (result.ok) logAudit(username, 'delete', 'assignment', assignmentId, `Deleted assignment ${assignmentId}`, before, null); return redirectWithFlash(reply, '/staffing', result.ok ? 'Assignment deleted.' : result.detail); });

  app.get('/dashboard', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fdashboard'); return reply.type('text/html; charset=utf-8').send(renderReactAuthedPage(app, 'dashboard', 'Matrix Manager · Dashboard', username, '/dashboard', String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });
  app.post('/dashboard/tracked/add', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fdashboard'); try { const employeeId = Number(asBody(request.body).employee_id); const current = getDashboardData(username); const next = updateDashboardTrackedEmployees(username, { employee_ids: [...new Set(current.tracked_employees.map((employee) => employee.id).concat(employeeId))] }); logAudit(username, 'update', 'dashboard_preferences', username, `Added employee ${employeeId} to tracked dashboard list`, current, next); return redirectWithFlash(reply, '/dashboard', 'Employee added to tracked list.'); } catch (error) { return redirectWithFlash(reply, '/dashboard', formatWorkforceError(error).detail); } });
  app.post('/dashboard/tracked/remove', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fdashboard'); try { const employeeId = Number(asBody(request.body).employee_id); const current = getDashboardData(username); const next = updateDashboardTrackedEmployees(username, { employee_ids: current.tracked_employees.map((employee) => employee.id).filter((id) => id !== employeeId) }); logAudit(username, 'update', 'dashboard_preferences', username, `Removed employee ${employeeId} from tracked dashboard list`, current, next); return redirectWithFlash(reply, '/dashboard', 'Employee removed from tracked list.'); } catch (error) { return redirectWithFlash(reply, '/dashboard', formatWorkforceError(error).detail); } });
  app.get('/forecast', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fforecast'); return reply.type('text/html; charset=utf-8').send(renderReactAuthedPage(app, 'forecast', 'Matrix Manager · Forecast', username, '/forecast', String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });

  app.get('/inbox', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Finbox'); return reply.type('text/html; charset=utf-8').send(buildInboxPage(username, listInboxItems(username), String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });
  app.post('/inbox/:itemId/read', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Finbox'); const itemId = Number((request.params as { itemId: string }).itemId); markInboxItemRead(username, itemId); logAudit(username, 'read', 'inbox_item', itemId, `Marked inbox item ${itemId} read`); return redirectWithFlash(reply, '/inbox', 'Inbox item marked read.'); });
  app.post('/inbox/:itemId/delete', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Finbox'); const itemId = Number((request.params as { itemId: string }).itemId); deleteInboxItem(username, itemId); logAudit(username, 'delete', 'inbox_item', itemId, `Dismissed inbox item ${itemId}`); return redirectWithFlash(reply, '/inbox', 'Inbox item dismissed.'); });

  app.get('/account-settings', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Faccount-settings'); return reply.type('text/html; charset=utf-8').send(buildAccountSettingsPage(username, getAccountSettings(username), String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });
  app.post('/account-settings/update', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Faccount-settings'); const body = asBody(request.body); const result = updateAccountSettings(username, { display_name: stringOrNull(body.display_name), profile_picture_url: stringOrNull(body.profile_picture_url), password: stringOrNull(body.password) }); logAudit(username, 'update', 'account', username, 'Updated account settings', result.before, result.after); return redirectWithFlash(reply, '/account-settings', 'Account settings updated.'); });

  app.get('/users', async (request, reply) => { const username = getSessionUsername(request); const guard = requireAdmin(reply, username); if (guard) return guard; return reply.type('text/html; charset=utf-8').send(buildUsersPage(username!, listUsers(), listEmployees().map((employee) => ({ id: employee.id, name: employee.name })), String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });
  app.post('/users/create', async (request, reply) => { const username = getSessionUsername(request); const guard = requireAdmin(reply, username); if (guard) return guard; try { const body = asBody(request.body); const created = createUser({ username: String(body.username ?? ''), password: String(body.password ?? ''), employee_id: numberOrNull(body.employee_id), is_admin: checkboxValue(body.is_admin) }) as { id: number; username: string }; logAudit(username!, 'create', 'user', created.id, `Created user ${created.username}`, null, created); return redirectWithFlash(reply, '/users', 'User created.'); } catch (error) { return redirectWithFlash(reply, '/users', String(error instanceof Error ? error.message : 'Failed to create user')); } });
  app.post('/users/:userId/update', async (request, reply) => { const username = getSessionUsername(request); const guard = requireAdmin(reply, username); if (guard) return guard; try { const userId = Number((request.params as { userId: string }).userId); const body = asBody(request.body); const updated = updateUser(userId, { password: stringOrNull(body.password), employee_id: numberOrNull(body.employee_id), is_admin: checkboxValue(body.is_admin) }); if (!updated) return redirectWithFlash(reply, '/users', 'User not found.'); logAudit(username!, 'update', 'user', userId, `Updated user ${updated.username}`, null, updated); return redirectWithFlash(reply, '/users', 'User updated.'); } catch (error) { return redirectWithFlash(reply, '/users', String(error instanceof Error ? error.message : 'Failed to update user')); } });
  app.post('/users/:userId/delete', async (request, reply) => { const username = getSessionUsername(request); const guard = requireAdmin(reply, username); if (guard) return guard; const userId = Number((request.params as { userId: string }).userId); const result = deleteUser(userId); if (result.ok) logAudit(username!, 'delete', 'user', userId, `Deleted user ${userId}`); return redirectWithFlash(reply, '/users', result.ok ? 'User deleted.' : result.detail); });

  app.get('/audit', async (request, reply) => { const username = getSessionUsername(request); const guard = requireAdmin(reply, username); if (guard) return guard; const query = (request.query as Record<string, unknown> | undefined) ?? {}; return reply.type('text/html; charset=utf-8').send(buildAuditPage(username!, listAuditEntries({ entity_type: String(query.entity_type ?? ''), action: String(query.action ?? ''), actor: String(query.actor ?? ''), query: String(query.query ?? '') }), String(query.flash ?? ''))); });
  app.post('/audit/clear', async (request, reply) => { const username = getSessionUsername(request); const guard = requireAdmin(reply, username); if (guard) return guard; clearAuditLog(username!); return redirectWithFlash(reply, '/audit', 'Audit history cleared.'); });

  app.get('/runtime', async (request, reply) => { const username = getSessionUsername(request); const guard = requireAdmin(reply, username); if (guard) return guard; return reply.type('text/html; charset=utf-8').send(buildRuntimePage(username!, getRuntimeOverview(), String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });

  app.get('/db-management', async (request, reply) => { const username = getSessionUsername(request); const guard = requireAdmin(reply, username); if (guard) return guard; return reply.type('text/html; charset=utf-8').send(buildDbManagementPage(username!, listDbConnections(), String((request.query as Record<string, unknown> | undefined)?.flash ?? ''))); });
  app.post('/db-management/create', async (request, reply) => { const username = getSessionUsername(request); const guard = requireAdmin(reply, username); if (guard) return guard; try { const body = asBody(request.body); const created = createDbConnection({ name: String(body.name ?? ''), db_type: String(body.db_type ?? 'sqlite') === 'postgresql' ? 'postgresql' : 'sqlite', connection_string: String(body.connection_string ?? ''), is_active: checkboxValue(body.is_active), notes: stringOrNull(body.notes) }) as { id: number; name: string }; logAudit(username!, 'create', 'db_connection', created.id, `Created DB connection ${created.name}`, null, created); return redirectWithFlash(reply, '/db-management', 'Connection saved.'); } catch (error) { return redirectWithFlash(reply, '/db-management', String(error instanceof Error ? error.message : 'Failed to save connection')); } });
  app.post('/db-management/:connectionId/update', async (request, reply) => { const username = getSessionUsername(request); const guard = requireAdmin(reply, username); if (guard) return guard; try { const connectionId = Number((request.params as { connectionId: string }).connectionId); const body = asBody(request.body); const updated = updateDbConnection(connectionId, { name: String(body.name ?? ''), db_type: String(body.db_type ?? 'sqlite') === 'postgresql' ? 'postgresql' : 'sqlite', connection_string: String(body.connection_string ?? ''), is_active: checkboxValue(body.is_active), notes: stringOrNull(body.notes) }); if (!updated) return redirectWithFlash(reply, '/db-management', 'Connection not found.'); logAudit(username!, 'update', 'db_connection', updated.id, `Updated DB connection ${updated.name}`, null, updated); return redirectWithFlash(reply, '/db-management', 'Connection updated.'); } catch (error) { return redirectWithFlash(reply, '/db-management', String(error instanceof Error ? error.message : 'Failed to update connection')); } });
  app.post('/db-management/:connectionId/delete', async (request, reply) => { const username = getSessionUsername(request); const guard = requireAdmin(reply, username); if (guard) return guard; const connectionId = Number((request.params as { connectionId: string }).connectionId); const result = deleteDbConnection(connectionId); if (result.ok) logAudit(username!, 'delete', 'db_connection', connectionId, `Deleted DB connection ${connectionId}`); return redirectWithFlash(reply, '/db-management', result.ok ? 'Connection deleted.' : result.detail); });
  app.post('/db-management/wipe-data-db', async (request, reply) => { const username = getSessionUsername(request); const guard = requireAdmin(reply, username); if (guard) return guard; const confirmation = String(asBody(request.body).confirmation_text ?? '').trim(); if (confirmation !== 'WIPE DATA DB') return redirectWithFlash(reply, '/db-management', 'Type WIPE DATA DB exactly to confirm.'); wipeDataStore(); logAudit(username!, 'wipe', 'data_store', 'api-workforce.json', 'Wiped TypeScript workforce data store'); return redirectWithFlash(reply, '/db-management', 'TypeScript data store wiped.'); });

  app.get('/session', async (request, reply) => { const username = getSessionUsername(request); if (!username) return reply.redirect('/login?next=%2Fsession'); return { authenticated: true, username, is_admin: isAdminUser(username) }; });
};

export function renderLoginError(app: Parameters<FastifyPluginAsync>[0], error: string, next: string) { return renderLogin(app, error, next); }
