import { renderAppChrome } from './chrome.js';

interface EmployeeOption { id: number; name: string; }
interface UserView { id: number; username: string; employee_id: number | null; employee_name?: string | null; is_admin: boolean; created_at: string; updated_at: string; }
interface AccountView { username: string; display_name: string | null; profile_picture_url: string | null; employee_id: number | null; employee_name?: string | null; is_admin: boolean; is_env_account: boolean; }
interface InboxItemView { id: number; kind: string; title: string; body: string; href: string; created_at: string; is_read: boolean; }
interface AuditEntryView { id: number; at: string; actor: string; action: string; entity_type: string; entity_id: string; summary: string; before_json: string | null; after_json: string | null; }
interface DbConnectionView { id: number; name: string; db_type: 'sqlite' | 'postgresql'; connection_string: string; is_active: boolean; notes: string | null; }
interface RuntimeView { overview: { overall_status: string; runtime_environment: string; active_data_db_status: string; control_db_status: string; docker_available: boolean; docker_error: string | null; recent_error_count: number; recommended_actions: string[]; services: Array<{ name: string; status: string; detail: string }>; installed_versions: Array<{ name: string; value: string }>; db_connections: Array<{ name: string; db_type: string; status: string; detail: string }>; }; snapshots: Array<{ id: number; at: string; key: string; status: string; value: string; detail: string }>; errorGroups: Array<object>; errors: Array<object>; recentAudit: AuditEntryView[]; }

function escapeHtml(input: string): string { return input.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;'); }

function layout(title: string, currentUser: string, currentPath: string, body: string, flash = ''): string {
  const chrome = renderAppChrome(currentUser, currentPath);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>${escapeHtml(title)}</title><style>*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:#f8fafc;color:#0f172a}${chrome.css}.wrap{max-width:1260px;margin:0 auto;padding:28px 16px 44px}.grid{display:grid;grid-template-columns:380px minmax(0,1fr);gap:20px;align-items:start;margin-top:24px}.stack{display:grid;gap:16px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:20px;box-shadow:0 10px 30px rgba(15,23,42,.05)}h1{margin:0 0 8px;font-size:38px}.lead{color:#475569;max-width:900px;line-height:1.7}.subtle{color:#64748b;font-size:13px}.flash{margin:0 0 16px;border:1px solid #bbf7d0;background:#f0fdf4;color:#166534;border-radius:12px;padding:12px 14px}label{display:block;margin:14px 0 6px;font-size:14px;font-weight:600}input,textarea,select{width:100%;padding:12px 14px;border:1px solid #cbd5e1;border-radius:10px;font:inherit;background:white}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px 10px;border-bottom:1px solid #e2e8f0;vertical-align:top}th{font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:#64748b}button.primary{margin-top:16px;padding:12px 14px;border:0;border-radius:10px;background:#0f172a;color:white;font-weight:700;cursor:pointer}button.secondary{padding:10px 12px;border:1px solid #cbd5e1;border-radius:10px;background:white;color:#0f172a;font-weight:600;cursor:pointer}button.danger{padding:10px 12px;border:1px solid #fecaca;border-radius:10px;background:#fff1f2;color:#b91c1c;font-weight:600;cursor:pointer}.actions{display:flex;gap:8px;flex-wrap:wrap}.badge{display:inline-flex;padding:4px 8px;border-radius:999px;background:#e2e8f0;color:#0f172a;font-size:12px;font-weight:700}.status-ok{background:#dcfce7;color:#166534}.status-warn{background:#fef3c7;color:#92400e}.status-error{background:#fee2e2;color:#991b1b}.pill-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:20px}.pill{padding:14px 16px;border-radius:14px;background:#fff;border:1px solid #e2e8f0}.pill strong{display:block;font-size:28px}.empty{color:#64748b}.cols-2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.meta{color:#64748b;font-size:14px;margin-top:24px}pre{white-space:pre-wrap;word-break:break-word;background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:10px}@media (max-width:980px){.grid{grid-template-columns:1fr}.pill-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.cols-2{grid-template-columns:1fr}}</style></head><body>${chrome.html}<main class="wrap">${flash ? `<div class="flash">${escapeHtml(flash)}</div>` : ''}${body}<div class="meta">Signed in as <strong>${escapeHtml(currentUser)}</strong></div></main></body></html>`;
}

export function buildUsersPage(currentUser: string, users: UserView[], employees: EmployeeOption[], flash = '') {
  const employeeOptions = ['<option value="">No linked employee</option>'].concat(employees.map((employee) => `<option value="${employee.id}">${escapeHtml(employee.name)}</option>`)).join('');
  const rows = users.length ? users.map((user) => `<tr><td><strong>${escapeHtml(user.username)}</strong><div class="subtle">Updated ${escapeHtml(user.updated_at)}</div></td><td>${escapeHtml(user.employee_name || '—')}</td><td>${user.is_admin ? '<span class="badge">Admin</span>' : '<span class="badge">User</span>'}</td><td><div class="stack"><form method="post" action="/users/${user.id}/update"><label>Linked employee</label><select name="employee_id">${['<option value="">No linked employee</option>'].concat(employees.map((employee) => `<option value="${employee.id}" ${user.employee_id === employee.id ? 'selected' : ''}>${escapeHtml(employee.name)}</option>`)).join('')}</select><label>New password</label><input type="password" name="password" placeholder="Leave blank to keep current" /><label><input type="checkbox" name="is_admin" ${user.is_admin ? 'checked' : ''} /> Admin</label><div class="actions"><button class="secondary" type="submit">Save</button></div></form><form method="post" action="/users/${user.id}/delete" onsubmit="return confirm('Delete ${escapeHtml(user.username)}?');"><button class="danger" type="submit">Delete</button></form></div></td></tr>`).join('') : '<tr><td colspan="4" class="empty">No TS user accounts yet.</td></tr>';
  return layout('Matrix Manager · Users', currentUser, '/users', `<h1>Users</h1><p class="lead">Manage TypeScript-side Matrix Manager accounts. These accounts can sign in alongside the bootstrap env login and can optionally be linked to employees for dashboard and account context.</p><div class="grid"><section class="card"><h2>Create user</h2><form method="post" action="/users/create"><label>Username</label><input name="username" required /><label>Password</label><input type="password" name="password" required /><label>Linked employee</label><select name="employee_id">${employeeOptions}</select><label><input type="checkbox" name="is_admin" /> Admin</label><button class="primary" type="submit">Create user</button></form></section><section class="card"><h2>Current users</h2><table><thead><tr><th>User</th><th>Employee</th><th>Role</th><th>Actions</th></tr></thead><tbody>${rows}</tbody></table></section></div>`, flash);
}

export function buildAccountSettingsPage(currentUser: string, account: AccountView, flash = '') {
  return layout('Matrix Manager · Account Settings', currentUser, '/account-settings', `<h1>Account Settings</h1><p class="lead">Update the current signed-in profile. Display name and avatar are persisted for all accounts; password changes are only applied for TypeScript-managed users.</p><div class="grid"><section class="card"><h2>Profile</h2><form method="post" action="/account-settings/update"><label>Username</label><input value="${escapeHtml(account.username)}" disabled /><label>Display name</label><input name="display_name" value="${escapeHtml(account.display_name || '')}" /><label>Profile picture URL</label><input name="profile_picture_url" value="${escapeHtml(account.profile_picture_url || '')}" placeholder="https://..." /><label>New password</label><input type="password" name="password" placeholder="Leave blank to keep current password" ${account.is_env_account ? 'disabled' : ''} /><button class="primary" type="submit">Save settings</button></form></section><section class="card"><h2>Current account</h2><div class="stack"><div><div class="subtle">Linked employee</div><strong>${escapeHtml(account.employee_name || 'No linked employee')}</strong></div><div><div class="subtle">Role</div><strong>${account.is_admin ? 'Admin' : 'Standard user'}</strong></div><div><div class="subtle">Account source</div><strong>${account.is_env_account ? 'Bootstrap env login (profile editable, password fixed in env)' : 'TypeScript user account'}</strong></div>${account.profile_picture_url ? `<div><div class="subtle">Avatar preview</div><img src="${escapeHtml(account.profile_picture_url)}" alt="Avatar" style="margin-top:8px;max-width:180px;border-radius:14px;border:1px solid #e2e8f0" /></div>` : ''}</div></section></div>`, flash);
}

export function buildInboxPage(currentUser: string, items: InboxItemView[], flash = '') {
  const content = items.length ? items.map((item) => `<article class="card" style="margin-top:16px;border-left:4px solid ${item.is_read ? '#cbd5e1' : '#0f172a'}"><div class="actions" style="justify-content:space-between;align-items:flex-start"><div><div class="subtle">${escapeHtml(item.kind)} · ${escapeHtml(item.created_at)}</div><h2 style="margin:6px 0 8px;font-size:22px">${escapeHtml(item.title)}</h2><p style="margin:0;color:#475569;line-height:1.7">${escapeHtml(item.body)}</p></div><div class="stack" style="min-width:160px"><a href="${escapeHtml(item.href)}" class="badge" style="text-decoration:none;justify-content:center">Open</a><form method="post" action="/inbox/${item.id}/read"><button class="secondary" type="submit">${item.is_read ? 'Mark seen' : 'Mark read'}</button></form><form method="post" action="/inbox/${item.id}/delete"><button class="danger" type="submit">Dismiss</button></form></div></div></article>`).join('') : '<section class="card"><p class="empty">No inbox items right now.</p></section>';
  return layout('Matrix Manager · Inbox', currentUser, '/inbox', `<h1>Inbox</h1><p class="lead">This TypeScript inbox rolls up actionable staffing signals from dashboard utilization, forecast gaps, and recent audit activity. It is intentionally simple but already useful for daily review.</p>${content}`, flash);
}

export function buildAuditPage(currentUser: string, entries: AuditEntryView[], flash = '') {
  const rows = entries.length ? entries.map((entry) => `<tr><td>${escapeHtml(entry.at)}</td><td>${escapeHtml(entry.actor)}</td><td>${escapeHtml(entry.action)}</td><td>${escapeHtml(entry.entity_type)}</td><td>${escapeHtml(entry.entity_id)}</td><td>${escapeHtml(entry.summary)}</td><td><pre>${escapeHtml(entry.before_json || '—')}</pre></td><td><pre>${escapeHtml(entry.after_json || '—')}</pre></td></tr>`).join('') : '<tr><td colspan="8" class="empty">No audit entries match the current filter.</td></tr>';
  return layout('Matrix Manager · Audit', currentUser, '/audit', `<h1>Audit</h1><p class="lead">Review TypeScript-side audit history for migrated page actions. This currently tracks the parity block plus the migrated CRUD routes as they move across.</p><div class="grid"><section class="card"><h2>Filter</h2><form method="get" action="/audit"><label>Entity type</label><input name="entity_type" /><label>Action</label><input name="action" /><label>Actor</label><input name="actor" /><label>Query</label><input name="query" /><button class="primary" type="submit">Apply filter</button></form><form method="post" action="/audit/clear" onsubmit="return confirm('Clear the audit log?');"><button class="danger" type="submit">Clear audit history</button></form></section><section class="card"><h2>Entries</h2><table><thead><tr><th>At</th><th>Actor</th><th>Action</th><th>Entity</th><th>ID</th><th>Summary</th><th>Before</th><th>After</th></tr></thead><tbody>${rows}</tbody></table></section></div>`, flash);
}

export function buildRuntimePage(currentUser: string, runtime: RuntimeView, flash = '') {
  const pills = [
    { label: 'Overall', value: runtime.overview.overall_status },
    { label: 'Data DB', value: runtime.overview.active_data_db_status },
    { label: 'Control DB', value: runtime.overview.control_db_status },
    { label: 'Recent errors', value: String(runtime.overview.recent_error_count) }
  ].map((item) => `<div class="pill"><span class="subtle">${escapeHtml(item.label)}</span><strong>${escapeHtml(item.value)}</strong></div>`).join('');
  const services = runtime.overview.services.map((service) => `<tr><td>${escapeHtml(service.name)}</td><td><span class="badge ${service.status === 'ok' ? 'status-ok' : service.status === 'warn' ? 'status-warn' : 'status-error'}">${escapeHtml(service.status)}</span></td><td>${escapeHtml(service.detail)}</td></tr>`).join('');
  const snapshots = runtime.snapshots.map((snapshot) => `<tr><td>${escapeHtml(snapshot.at)}</td><td>${escapeHtml(snapshot.key)}</td><td>${escapeHtml(snapshot.value)}</td><td><span class="badge ${snapshot.status === 'ok' ? 'status-ok' : 'status-warn'}">${escapeHtml(snapshot.status)}</span></td><td>${escapeHtml(snapshot.detail)}</td></tr>`).join('');
  const versions = runtime.overview.installed_versions.map((row) => `<tr><td>${escapeHtml(row.name)}</td><td>${escapeHtml(row.value)}</td></tr>`).join('');
  const dbs = runtime.overview.db_connections.length ? runtime.overview.db_connections.map((row) => `<tr><td>${escapeHtml(row.name)}</td><td>${escapeHtml(row.db_type)}</td><td>${escapeHtml(row.status)}</td><td>${escapeHtml(row.detail)}</td></tr>`).join('') : '<tr><td colspan="4" class="empty">No DB connections have been configured.</td></tr>';
  const audit = runtime.recentAudit.length ? runtime.recentAudit.map((entry) => `<li>${escapeHtml(entry.at)} · ${escapeHtml(entry.summary)}</li>`).join('') : '<li class="empty">No recent audit entries.</li>';
  return layout('Matrix Manager · Runtime', currentUser, '/runtime', `<h1>Runtime</h1><p class="lead">Operational summary for the TypeScript runtime, JSON stores, configured DB profiles, and a small health snapshot of migrated data volumes.</p><div class="pill-grid">${pills}</div><div class="grid"><section class="stack"><article class="card"><h2>Recommendations</h2>${runtime.overview.recommended_actions.length ? `<ul>${runtime.overview.recommended_actions.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul>` : '<p class="empty">No immediate recommendations.</p>'}</article><article class="card"><h2>Recent audit</h2><ul>${audit}</ul></article><article class="card"><h2>Installed versions</h2><table><tbody>${versions}</tbody></table></article></section><section class="stack"><article class="card"><h2>Services</h2><table><thead><tr><th>Service</th><th>Status</th><th>Detail</th></tr></thead><tbody>${services}</tbody></table></article><article class="card"><h2>Snapshots</h2><table><thead><tr><th>At</th><th>Key</th><th>Value</th><th>Status</th><th>Detail</th></tr></thead><tbody>${snapshots}</tbody></table></article><article class="card"><h2>DB connections</h2><table><thead><tr><th>Name</th><th>Type</th><th>Status</th><th>Detail</th></tr></thead><tbody>${dbs}</tbody></table></article></section></div>`, flash);
}

export function buildDbManagementPage(currentUser: string, connections: DbConnectionView[], flash = '') {
  const rows = connections.length ? connections.map((connection) => `<tr><td><strong>${escapeHtml(connection.name)}</strong></td><td>${escapeHtml(connection.db_type)}</td><td>${connection.is_active ? '<span class="badge status-ok">Active</span>' : '<span class="badge">Saved</span>'}</td><td><code>${escapeHtml(connection.connection_string)}</code></td><td>${escapeHtml(connection.notes || '—')}</td><td><div class="stack"><form method="post" action="/db-management/${connection.id}/update"><label>Name</label><input name="name" value="${escapeHtml(connection.name)}" required /><div class="cols-2"><select name="db_type"><option value="sqlite" ${connection.db_type === 'sqlite' ? 'selected' : ''}>sqlite</option><option value="postgresql" ${connection.db_type === 'postgresql' ? 'selected' : ''}>postgresql</option></select><label><input type="checkbox" name="is_active" ${connection.is_active ? 'checked' : ''} /> Active</label></div><label>Connection string</label><input name="connection_string" value="${escapeHtml(connection.connection_string)}" required /><label>Notes</label><textarea name="notes" rows="2">${escapeHtml(connection.notes || '')}</textarea><div class="actions"><button class="secondary" type="submit">Save</button></div></form><form method="post" action="/db-management/${connection.id}/delete" onsubmit="return confirm('Delete ${escapeHtml(connection.name)}?');"><button class="danger" type="submit">Delete</button></form></div></td></tr>`).join('') : '<tr><td colspan="6" class="empty">No connection profiles saved yet.</td></tr>';
  return layout('Matrix Manager · DB Management', currentUser, '/db-management', `<h1>DB Management</h1><p class="lead">Manage TypeScript-side connection profiles and inspect which target is marked active. For parity right now this is an operator-facing control surface rather than a live connector switcher.</p><div class="grid"><section class="stack"><article class="card"><h2>Create connection</h2><form method="post" action="/db-management/create"><label>Name</label><input name="name" required /><div class="cols-2"><div><label>DB type</label><select name="db_type"><option value="sqlite">sqlite</option><option value="postgresql">postgresql</option></select></div><div><label><input type="checkbox" name="is_active" /> Active</label></div></div><label>Connection string</label><input name="connection_string" required /><label>Notes</label><textarea name="notes" rows="4"></textarea><button class="primary" type="submit">Save connection</button></form></article><article class="card"><h2>Danger zone</h2><p class="subtle">Wipe the TypeScript data store used by the migrated app surfaces. This resets organizations, job codes, employees, projects, demands, assignments, and dashboard preferences.</p><form method="post" action="/db-management/wipe-data-db" onsubmit="return confirm('Wipe the TypeScript data store?');"><label>Confirmation text</label><input name="confirmation_text" placeholder="WIPE DATA DB" required /><button class="danger" type="submit">Wipe data store</button></form></article></section><section class="card"><h2>Saved connections</h2><table><thead><tr><th>Name</th><th>Type</th><th>Status</th><th>Connection</th><th>Notes</th><th>Actions</th></tr></thead><tbody>${rows}</tbody></table></section></div>`, flash);
}
